[build]
  functions = "functions"
  NODE_ENV="production"

[functions]
  directory="functions/"
  node_bundler="esbuild"
  external_node_modules = ["json-server"]

[context.production]
  NODE_ENV="production"